ATTENDANCE_BUTTON_ID = 'btnIN1'
LEAVING_BUTTON_ID = 'btnIN2'
ATTENDANCE_BUTTON_PUSHED_XPATH = '//*[@id="stamping"]/a[1]'
LEAVING_BUTTON_PUSHED_XPATH = '//*[@id="stamping"]/a[2]'
USER_BOX_ID = 'user_login_id'
PASSWORD_BOX_ID = 'user_password'
IEYASU_LOGIN_BUTTON_XPATH = '//*[@id="new_user"]/div[2]/input'
IEYASU_TIMESTAMP_URL = 'https://f.ieyasu.co/timestamp'
