ATTENDANCE_BUTTON_XPATH = '//*[@id="btnIN1"]'
LEAVING_BUTTON_XPATH = '//*[@id="stamping"]/a[2]'
USER_BOX_ID = 'user_login_id'
PASSWORD_BOX_ID = 'user_password'
IEYASU_LOGIN_BUTTON_XPATH = '//*[@id="new_user"]/div[2]/input'
IEYASU_TIMESTAMP_URL = 'https://f.ieyasu.co/timestamp'
